"""Install an official-ToG adapted oracle-subgraph + DiPLaN runner.

This patch does NOT use the simplified DiPLaN ``run_tog_subgraph_planning_eval.py``.
Instead it writes a new entrypoint inside a cloned official ToG repository:

    <ToG>/ToG/main_subgraph_diplan.py

The entrypoint keeps the official ToG loop shape and reuses official ToG utility
functions/prompts where possible, but replaces the Freebase SPARQL backend with
per-question oracle subgraphs from ``data/rog_processed/*.jsonl``. DiPLaN is
inserted as a candidate-conditioned reranker over ToG-generated candidates.

Run on the server:

    python scripts/patch_official_tog_subgraph_diplan.py \
      --tog_dir /root/autodl-tmp/paper_baselines/ToG
"""

from __future__ import annotations

import argparse
from pathlib import Path


MAIN_SUBGRAPH_DIPLAN = r'''"""Official-ToG adapted oracle-subgraph runner with DiPLaN reranking.

This file is generated by DiPLaN's patch_official_tog_subgraph_diplan.py.

It intentionally lives inside the official ToG repo and reuses ToG's utility
functions/prompts. The only backend change is replacing live Freebase SPARQL with
per-question local oracle subgraphs. DiPLaN is added at the candidate selection
stage as a candidate-conditioned reranker.
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path
from statistics import mean

from tqdm import tqdm

from utils import (  # official ToG utilities
    clean_relations,
    construct_relation_prune_prompt,
    construct_entity_score_prompt,
    clean_scores,
    update_history,
    entity_prune,
)
import utils as tog_utils


def run_llm(prompt, temperature, max_tokens, opeani_api_keys, engine="gpt-3.5-turbo"):
    """OpenAI-compatible transport for vLLM/Ollama while preserving ToG signature."""
    import os
    import time
    import urllib.request
    import urllib.error

    api_base = os.environ.get("TOG_OPENAI_API_BASE", "http://127.0.0.1:8000/v1").rstrip("/")
    api_key = os.environ.get("TOG_OPENAI_API_KEY", opeani_api_keys or "EMPTY")
    model = os.environ.get("TOG_OPENAI_MODEL", engine)
    timeout_s = int(os.environ.get("TOG_LLM_TIMEOUT_S", "60"))
    retries = int(os.environ.get("TOG_LLM_RETRIES", "2"))
    max_tokens = min(int(max_tokens), int(os.environ.get("TOG_LLM_MAX_OUTPUT_TOKENS", "96")))
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "You are a knowledge-graph reasoning assistant."},
            {"role": "user", "content": prompt},
        ],
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    data = json.dumps(payload).encode("utf-8")
    headers = {"Content-Type": "application/json", "Authorization": f"Bearer {api_key}"}
    url = api_base + "/chat/completions"
    last_err = None
    for attempt in range(1, max(1, retries) + 1):
        try:
            req = urllib.request.Request(url, data=data, headers=headers, method="POST")
            with urllib.request.urlopen(req, timeout=timeout_s) as resp:
                obj = json.loads(resp.read().decode("utf-8"))
            return str(obj["choices"][0]["message"]["content"]).strip()
        except urllib.error.HTTPError as exc:
            last_err = f"HTTP {exc.code}: {exc.read().decode('utf-8', errors='ignore')[:300]}"
            if exc.code == 400:
                raise RuntimeError(last_err)
        except Exception as exc:
            last_err = str(exc)
        print(f"[ToG LLM] attempt {attempt}/{retries} failed: {last_err}", flush=True)
        time.sleep(min(2 * attempt, 8))
    raise RuntimeError(f"ToG LLM call failed after {retries} retries: {last_err}")


def _repo_root_from_diplan_arg(path: str) -> Path:
    p = Path(path).expanduser().resolve()
    if not p.exists():
        raise FileNotFoundError(p)
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))
    return p


def _load_jsonl(path: str, max_tasks: int = 0):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
            if max_tasks > 0 and len(rows) >= max_tasks:
                break
    return rows


def _as_list(x):
    if x is None:
        return []
    if isinstance(x, str):
        return [x]
    return list(x)


class LocalSubgraphBackend:
    def __init__(self, row: dict):
        self.row = row
        self.question = row["question"]
        self.answers = {str(x) for x in _as_list(row.get("a_entity"))}
        self.oracle_path = list(row.get("oracle_path") or [])
        self.trap_path = list(row.get("trap_path") or [])
        self.q_entity = _as_list(row.get("q_entity"))
        self.adj = {}
        self.rev = {}
        self.names = set()
        for s, r, o in row.get("graph") or []:
            s, r, o = str(s), str(r), str(o)
            self.adj.setdefault(s, {}).setdefault(r, [])
            if o not in self.adj[s][r]:
                self.adj[s][r].append(o)
            self.rev.setdefault(o, {}).setdefault(r, [])
            if s not in self.rev[o][r]:
                self.rev[o][r].append(s)
            self.names.add(s)
            self.names.add(o)

    def id2name(self, entity_id: str) -> str:
        return str(entity_id)

    def topic_entity(self):
        return {str(e): self.id2name(str(e)) for e in self.q_entity}

    def relations(self, entity_id: str, pre_relations, pre_head, remove_unnecessary=True):
        head_relations = sorted(self.adj.get(entity_id, {}).keys())
        tail_relations = sorted(self.rev.get(entity_id, {}).keys())
        if remove_unnecessary:
            head_relations = [r for r in head_relations if not _abandon_rels(r)]
            tail_relations = [r for r in tail_relations if not _abandon_rels(r)]
        if len(pre_relations) != 0 and pre_head != -1:
            tail_relations = [r for r in tail_relations if pre_head or r not in pre_relations]
            head_relations = [r for r in head_relations if (not pre_head) or r not in pre_relations]
        return sorted(set(head_relations)), sorted(set(tail_relations))

    def entity_search(self, entity_id: str, relation: str, head=True):
        if head:
            return list(self.adj.get(entity_id, {}).get(relation, []))
        return list(self.rev.get(entity_id, {}).get(relation, []))


def _abandon_rels(relation: str) -> bool:
    return (
        relation == "type.object.type"
        or relation == "type.object.name"
        or relation.startswith("common.")
        or relation.startswith("freebase.")
        or "sameAs" in relation
    )


def relation_label(relation: str) -> str:
    return " ".join(t for t in relation.replace(".", " ").replace("_", " ").split() if t)


def relation_search_prune_local(backend: LocalSubgraphBackend, entity_id, entity_name, pre_relations, pre_head, question, args):
    head_relations, tail_relations = backend.relations(
        entity_id,
        pre_relations,
        pre_head,
        remove_unnecessary=bool(args.remove_unnecessary_rel),
    )
    total_relations = sorted(set(head_relations + tail_relations))
    if not total_relations:
        return []
    max_prompt_relations = int(getattr(args, "max_prompt_relations", 64))
    prompt_relations = sorted(total_relations, key=lambda r: (-_overlap(relation_label(r), question), r))[:max_prompt_relations]
    rerank_pool_size = 0
    if getattr(args, "planning_strategy", "tog") == "tog_diplan":
        rerank_pool_size = int(getattr(args, "diplan_rerank_pool_size", 0))
    if args.prune_tools == "llm":
        # Use official ToG relation-prune prompt, but expose human-readable labels
        # while keeping original relation IDs parseable by clean_relations.
        labelled = [f"{r} (label: {relation_label(r)})" for r in prompt_relations]
        prompt = construct_relation_prune_prompt(question, entity_name, labelled, args)
        try:
            result = run_llm(prompt, args.temperature_exploration, args.max_length, args.opeani_api_keys, args.LLM_type)
            # The official parser expects exact relation strings; strip labels before parse.
            for r in prompt_relations:
                result = result.replace(f"{r} (label: {relation_label(r)})", r)
            flag, rels = clean_relations(result, entity_id, head_relations)
            if flag:
                if rerank_pool_size > args.width:
                    return _expand_relation_pool(
                        entity_id, rels, total_relations, head_relations, question, rerank_pool_size
                    )
                return rels
        except Exception as exc:
            print(f"[ToG relation prune] LLM failed, fallback to lexical: {exc}", flush=True)
    # Deterministic fallback: relation-label lexical overlap.
    limit = rerank_pool_size if rerank_pool_size > args.width else args.width
    ranked = sorted(total_relations, key=lambda r: (-_overlap(relation_label(r), question), r))[: limit]
    return [
        {"entity": entity_id, "relation": r, "score": 1.0 / (i + 1), "head": r in head_relations}
        for i, r in enumerate(ranked)
    ]


def _expand_relation_pool(entity_id, seed_rels, total_relations, head_relations, question, pool_size):
    """Let ToG build the action space, then expose a larger legal pool to DiPLaN.

    Original ToG often returns only ``width`` relations (e.g. 3). If DiPLaN only
    reranks those three, it can look active while having almost no room to help.
    This keeps ToG/LLM relations first, then fills with lexical legal relations
    so candidate-conditioned DiPLaN can choose from top-k actions before we cut
    back to the execution width.
    """
    out = []
    seen = set()
    for i, item in enumerate(seed_rels or []):
        rel = item.get("relation") if isinstance(item, dict) else str(item)
        if rel in seen or rel not in total_relations:
            continue
        cc = dict(item) if isinstance(item, dict) else {}
        cc.setdefault("entity", entity_id)
        cc["relation"] = rel
        cc.setdefault("score", 1.0 / (i + 1))
        cc.setdefault("head", rel in head_relations)
        out.append(cc)
        seen.add(rel)
    ranked = sorted(total_relations, key=lambda r: (-_overlap(relation_label(r), question), r))
    for j, rel in enumerate(ranked):
        if len(out) >= pool_size:
            break
        if rel in seen:
            continue
        out.append({
            "entity": entity_id,
            "relation": rel,
            "score": 0.25 / (j + 1),
            "head": rel in head_relations,
        })
        seen.add(rel)
    return out


def _overlap(text: str, question: str) -> float:
    q = {t.lower() for t in question.replace("?", " ").replace(",", " ").split() if t}
    r = {t.lower() for t in text.replace(".", " ").replace("_", " ").split() if t}
    return len(q & r) / max(1, len(r))


def entity_score_local(backend: LocalSubgraphBackend, question, entity_candidates_id, score, relation, args):
    entity_candidates = [backend.id2name(eid) for eid in entity_candidates_id]
    if len(entity_candidates) == 0:
        return [0.0], [], []
    if len(entity_candidates) == 1:
        return [score], entity_candidates, entity_candidates_id
    if args.prune_tools == "llm":
        prompt = construct_entity_score_prompt(question, relation, entity_candidates)
        result = run_llm(prompt, args.temperature_exploration, args.max_length, args.opeani_api_keys, args.LLM_type)
        return [float(x) * score for x in clean_scores(result, entity_candidates)], entity_candidates, entity_candidates_id
    # fallback: keep equal mass
    return [score / len(entity_candidates)] * len(entity_candidates), entity_candidates, entity_candidates_id


class DiPLaNReranker:
    def __init__(self, args):
        self.enabled = bool(args.diplan_ae_ckpt and args.diplan_planner_ckpt)
        self.calls = 0
        self.candidate_count_sum = 0
        self.top_changed = 0
        self.value_std_sum = 0.0
        self.prior_std_sum = 0.0
        self.prior_nonzero_calls = 0
        if not self.enabled:
            return
        _repo_root_from_diplan_arg(args.diplan_repo)
        from src.diplan.planners import load_diffusion_bundle
        from src.diplan.inference import sample_plan_candidates, score_candidates_with_value

        self.sample_plan_candidates = sample_plan_candidates
        self.score_candidates_with_value = score_candidates_with_value
        self.bundle = load_diffusion_bundle(args.diplan_ae_ckpt, args.diplan_planner_ckpt, args.diplan_value_ckpt, {
            "diffusion": {
                "num_candidates": args.diplan_num_candidates,
                "diffusion_steps": args.diplan_diffusion_steps,
                "use_prefix": True,
                "jitter_std": args.diplan_jitter_std,
            }
        })
        self.value_weight = float(args.diplan_value_weight)
        self.prior_weight = float(args.diplan_prior_weight)
        self.first_step_bonus = float(args.diplan_first_step_bonus)
        self.future_step_bonus = float(args.diplan_future_step_bonus)
        self.prior_min_jaccard = float(args.diplan_prior_min_jaccard)
        self.horizon = int(args.diplan_horizon)
        self.planner_type = str(getattr(self.bundle, "planner_type", "unknown"))
        self.last_debug = None

    def rerank(self, backend: LocalSubgraphBackend, candidates, executed_prefix):
        if not self.enabled or not candidates:
            self.last_debug = None
            return candidates
        self.calls += 1
        self.candidate_count_sum += len(candidates)
        original_top = candidates[0]["relation"]
        before_top = _compact_relation_list(candidates, topk=8)
        query_tokens = list(backend.row.get("query_tokens") or backend.question.split())
        paths = [list(executed_prefix) + [c["relation"]] for c in candidates]
        raw_value_scores = self.score_candidates_with_value(
            self.bundle.value_model,
            self.bundle.path_vocab,
            self.bundle.query_vocab,
            query_tokens,
            paths,
            self.bundle.device,
            max_query_len=32,
            max_path_len=30,
        )
        self.value_std_sum += _std(raw_value_scores)
        value_scores = _z_norm(raw_value_scores)
        prior_scores = [0.0 for _ in candidates]
        sampled_paths = []
        if self.prior_weight != 0.0:
            sampled_paths = self.sample_plan_candidates(
                planner=self.bundle.planner,
                autoencoder=self.bundle.autoencoder,
                path_vocab=self.bundle.path_vocab,
                query_vocab=self.bundle.query_vocab,
                query_tokens=query_tokens,
                num_candidates=self.bundle.num_candidates,
                diffusion_steps=self.bundle.diffusion_steps,
                max_path_len=max(1, self.horizon),
                device=self.bundle.device,
                executed_prefix=list(executed_prefix),
                use_prefix=self.bundle.use_prefix,
                latent_mean=self.bundle.latent_mean,
                latent_std=self.bundle.latent_std,
                prediction_target=self.bundle.prediction_target,
                planner_type=self.bundle.planner_type,
                jitter_std=self.bundle.jitter_std,
            )
            prior_scores = _candidate_diffusion_prior(
                [c["relation"] for c in candidates],
                sampled_paths,
                first_bonus=self.first_step_bonus,
                future_bonus=self.future_step_bonus,
                min_jaccard=self.prior_min_jaccard,
            )
            self.prior_std_sum += _std(prior_scores)
            if any(abs(float(x)) > 1e-12 for x in prior_scores):
                self.prior_nonzero_calls += 1
            prior_scores = _z_norm(prior_scores)
        out = []
        for c, v, p in zip(candidates, value_scores, prior_scores):
            cc = dict(c)
            cc["diplan_value_score"] = float(v)
            cc["diplan_prior_score"] = float(p)
            cc["score"] = (
                float(cc["score"])
                + self.value_weight * float(v)
                + self.prior_weight * float(p)
            )
            out.append(cc)
        out = sorted(out, key=lambda x: x["score"], reverse=True)
        if out and out[0]["relation"] != original_top:
            self.top_changed += 1
        self.last_debug = {
            "num_candidates": len(candidates),
            "before_top": before_top,
            "after_top": _compact_relation_list(out, topk=8),
            "sampled_paths_top": sampled_paths[:5],
            "value_std": _std(raw_value_scores),
            "prior_std": _std(prior_scores),
            "top_changed": bool(out and out[0]["relation"] != original_top),
        }
        return out

    def diagnostics(self):
        denom = max(1, self.calls)
        return {
            "diplan_enabled": self.enabled,
            "diplan_planner_type": getattr(self, "planner_type", "disabled"),
            "diplan_rerank_calls": self.calls,
            "diplan_avg_candidates_per_call": self.candidate_count_sum / denom,
            "diplan_top_changed_rate": self.top_changed / denom,
            "diplan_value_std_mean": self.value_std_sum / denom,
            "diplan_prior_std_mean": self.prior_std_sum / denom,
            "diplan_prior_nonzero_rate": self.prior_nonzero_calls / denom,
        }


def _candidate_diffusion_prior(relations, sampled_paths, first_bonus=1.0, future_bonus=0.35, min_jaccard=0.2):
    """Soft-project diffusion trajectories back onto ToG's legal candidate actions.

    Diffusion is allowed to imagine a global future path, but the executed action
    must remain one of ToG's admissible graph relations. Exact first-step matches
    get the strongest signal; fuzzy/future matches are weaker trajectory priors.
    """
    scores = [0.0 for _ in relations]
    if not sampled_paths:
        return scores
    for path in sampled_paths:
        if not path:
            continue
        for i, rel in enumerate(relations):
            best = 0.0
            for j, tok in enumerate(path):
                sim = 1.0 if tok == rel else _semantic_relation_similarity(tok, rel)
                if sim < min_jaccard:
                    continue
                if j == 0:
                    bonus = first_bonus * sim
                else:
                    bonus = future_bonus * sim / (j + 1)
                if bonus > best:
                    best = bonus
            scores[i] += best
    denom = max(1, len(sampled_paths))
    return [s / denom for s in scores]


def _semantic_relation_similarity(a: str, b: str) -> float:
    """Robust relation matching for projecting generated paths to legal actions.

    Raw Freebase ids are brittle: ``countries_spoken_in`` and
    ``languages_spoken`` should be close, while a generic ``*.country`` edge
    should not steal all the prior mass. We use normalized relation tokens,
    relation-tail overlap, and a small noisy-namespace penalty.
    """
    aa = _relation_tokens_norm(a)
    bb = _relation_tokens_norm(b)
    if not aa or not bb:
        return 0.0
    inter = len(set(aa) & set(bb))
    union = len(set(aa) | set(bb))
    jaccard = inter / union if union else 0.0

    # Last tokens often carry the relation intent: languages_spoken, official_language.
    tail_a = set(aa[-3:])
    tail_b = set(bb[-3:])
    tail_union = len(tail_a | tail_b)
    tail = (len(tail_a & tail_b) / tail_union) if tail_union else 0.0

    # Directional coverage helps short canonical labels such as language/spoken.
    cover_b = inter / max(1, len(set(bb)))
    score = 0.45 * jaccard + 0.35 * tail + 0.20 * cover_b

    # Demote noisy bookkeeping namespaces that share only broad words like country.
    noisy = (
        b.startswith("base.biblioness.")
        or b.startswith("base.kwebbase.")
        or b.startswith("base.aareas.schema.")
    )
    if noisy and len(set(aa) & set(bb) & {"language", "speak", "spoken", "official"}) == 0:
        score *= 0.35
    return score


def _relation_tokens_norm(rel: str):
    out = []
    for raw in rel.lower().replace(".", " ").replace("_", " ").replace("-", " ").split():
        tok = raw.strip()
        if not tok or tok in {"base", "common", "freebase", "type", "object", "schema", "biblioness", "kwebbase"}:
            continue
        tok = _canonical_relation_token(tok)
        if tok:
            out.append(tok)
    return out


def _canonical_relation_token(tok: str) -> str:
    aliases = {
        "countries": "country",
        "locations": "location",
        "languages": "language",
        "speaks": "spoken",
        "speak": "spoken",
        "spoke": "spoken",
        "speaking": "spoken",
        "spoken": "spoken",
        "official": "official",
        "position": "position",
        "positions": "position",
        "held": "held",
        "office": "office",
        "offices": "office",
        "president": "president",
        "presidential": "president",
        "politicians": "politician",
        "works": "work",
        "written": "write",
        "wrote": "write",
        "writer": "write",
        "authors": "author",
        "ideas": "idea",
        "invented": "invent",
        "inventions": "invent",
        "innovator": "invent",
    }
    if tok in aliases:
        return aliases[tok]
    if len(tok) > 4 and tok.endswith("ies"):
        return tok[:-3] + "y"
    if len(tok) > 3 and tok.endswith("s"):
        return tok[:-1]
    return tok


def _compact_relation_list(items, topk=5):
    out = []
    for x in list(items)[:topk]:
        out.append({
            "relation": x.get("relation"),
            "score": round(float(x.get("score", 0.0)), 4),
            "value": round(float(x.get("diplan_value_score", 0.0)), 4),
            "prior": round(float(x.get("diplan_prior_score", 0.0)), 4),
            "head": bool(x.get("head", False)),
        })
    return out


def _relation_rank(items, target):
    if not target:
        return None
    for i, x in enumerate(items, start=1):
        rel = x.get("relation") if isinstance(x, dict) else str(x)
        if rel == target:
            return i
    return None


def _oracle_next_relation(backend: LocalSubgraphBackend, executed_prefix):
    oracle = list(backend.oracle_path or [])
    idx = len(executed_prefix)
    if idx < len(oracle):
        return oracle[idx]
    return None


def _relation_jaccard(a: str, b: str) -> float:
    aa = set(_relation_tokens_norm(a))
    bb = set(_relation_tokens_norm(b))
    if not aa or not bb:
        return 0.0
    return len(aa & bb) / len(aa | bb)


def _z_norm(xs):
    vals = [float(x) for x in xs]
    if not vals:
        return []
    mu = mean(vals)
    var = mean((x - mu) ** 2 for x in vals)
    std = var ** 0.5
    if std < 1e-8:
        return [0.0 for _ in vals]
    return [(x - mu) / std for x in vals]


def _std(xs):
    vals = [float(x) for x in xs]
    if not vals:
        return 0.0
    mu = mean(vals)
    return (mean((x - mu) ** 2 for x in vals)) ** 0.5


def answer_reached(backend: LocalSubgraphBackend, entity_ids) -> bool:
    return bool(set(str(x) for x in entity_ids) & backend.answers)


def _str2bool(x):
    if isinstance(x, bool):
        return x
    return str(x).lower() in {"1", "true", "yes", "y", "on"}


def _print_trace(task_no, trace_record, topk):
    print("\n" + "=" * 88, flush=True)
    print(f"[trace] task={task_no} id={trace_record.get('task_id')} success={trace_record.get('success')}", flush=True)
    print(f"[question] {trace_record.get('question')}", flush=True)
    print(f"[oracle] {trace_record.get('oracle_path')}", flush=True)
    print(f"[executed] {trace_record.get('executed_path')}", flush=True)
    for step in trace_record.get("steps", []):
        print(f"  step={step['depth']} topic_entities={step['topic_entities']}", flush=True)
        for ent in step.get("entity_expansions", []):
            print(
                f"    entity={ent['entity']} pool={ent['num_relations']} kept={len(ent.get('kept_after_rerank', []))} "
                f"oracle_next={ent.get('oracle_next_relation')} "
                f"rank_before={ent.get('oracle_rank_before_rerank')} "
                f"rank_after={ent.get('oracle_rank_after_rerank_full')} "
                f"rank_keep={ent.get('oracle_rank_after_keep')}",
                flush=True,
            )
            if ent.get("rerank"):
                rr = ent["rerank"]
                print(
                    f"      rerank changed={rr.get('top_changed')} value_std={rr.get('value_std'):.4f} prior_std={rr.get('prior_std'):.4f}",
                    flush=True,
                )
                print(f"      before={rr.get('before_top', [])[:topk]}", flush=True)
                print(f"      after ={rr.get('after_top', [])[:topk]}", flush=True)
                print(f"      sampled={rr.get('sampled_paths_top', [])[:2]}", flush=True)
            else:
                print(f"      rels={ent.get('kept_after_rerank', [])[:topk]}", flush=True)
        print(
            f"    selected_relations={step.get('selected_relations')} "
            f"oracle_selected={step.get('oracle_selected')} "
            f"selected_entities={step.get('selected_entities')} reached={step.get('answer_reached')}",
            flush=True,
        )
    print("=" * 88 + "\n", flush=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--subgraph_jsonl", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--max_tasks", type=int, default=20)
    parser.add_argument("--max_length", type=int, default=256)
    parser.add_argument("--max_prompt_relations", type=int, default=64)
    parser.add_argument("--temperature_exploration", type=float, default=0.4)
    parser.add_argument("--temperature_reasoning", type=float, default=0)
    parser.add_argument("--width", type=int, default=3)
    parser.add_argument("--depth", type=int, default=3)
    parser.add_argument("--remove_unnecessary_rel", type=bool, default=True)
    parser.add_argument("--LLM_type", type=str, default="Qwen3.5-35B-A3B-FP8")
    parser.add_argument("--opeani_api_keys", type=str, default="EMPTY")
    parser.add_argument("--num_retain_entity", type=int, default=5)
    parser.add_argument("--prune_tools", type=str, default="llm")
    parser.add_argument("--planning_strategy", type=str, default="tog_diplan", choices=["tog", "tog_diplan"])
    parser.add_argument("--diplan_repo", default="/root/autodl-tmp/DiPLaN")
    parser.add_argument("--diplan_ae_ckpt", default="")
    parser.add_argument("--diplan_planner_ckpt", default="")
    parser.add_argument("--diplan_value_ckpt", default="")
    parser.add_argument("--diplan_value_weight", type=float, default=1.0)
    parser.add_argument("--diplan_prior_weight", type=float, default=1.0)
    parser.add_argument("--diplan_first_step_bonus", type=float, default=1.0)
    parser.add_argument("--diplan_future_step_bonus", type=float, default=0.35)
    parser.add_argument("--diplan_prior_min_jaccard", type=float, default=0.2)
    parser.add_argument("--diplan_horizon", type=int, default=3)
    parser.add_argument("--diplan_rerank_pool_size", type=int, default=16)
    parser.add_argument("--diplan_post_rerank_topk", type=int, default=0)
    parser.add_argument("--diplan_num_candidates", type=int, default=16)
    parser.add_argument("--diplan_diffusion_steps", type=int, default=20)
    parser.add_argument("--diplan_jitter_std", type=float, default=0.05)
    parser.add_argument("--show_trace", type=_str2bool, default=False)
    parser.add_argument("--trace_limit", type=int, default=5)
    parser.add_argument("--trace_topk", type=int, default=5)
    args = parser.parse_args()

    rows = _load_jsonl(args.subgraph_jsonl, args.max_tasks)
    reranker = DiPLaNReranker(args) if args.planning_strategy == "tog_diplan" else None
    Path(args.out).mkdir(parents=True, exist_ok=True)
    pred_path = Path(args.out) / "predictions.jsonl"
    trace_path = Path(args.out) / "trace.jsonl"
    records = []
    with pred_path.open("w", encoding="utf-8") as fout, trace_path.open("w", encoding="utf-8") as ftrace:
        for task_idx, row in enumerate(tqdm(rows), start=1):
            backend = LocalSubgraphBackend(row)
            # Official ToG's entity_prune calls id2entity_name_or_type from utils'
            # global namespace. Override it per row so entity_prune stays official
            # but name lookup uses the local oracle subgraph instead of Freebase.
            tog_utils.id2entity_name_or_type = backend.id2name
            question = backend.question
            topic_entity = backend.topic_entity()
            cluster_chain_of_entities = []
            pre_relations = []
            pre_heads = [-1] * len(topic_entity)
            executed = []
            success = False
            trace_steps = []

            for depth in range(1, args.depth + 1):
                current_entity_relations_list = []
                step_trace = {
                    "depth": depth,
                    "topic_entities": dict(topic_entity),
                    "executed_prefix": list(executed),
                    "entity_expansions": [],
                }
                for i, entity in enumerate(list(topic_entity.keys())):
                    if entity == "[FINISH_ID]":
                        continue
                    oracle_next = _oracle_next_relation(backend, executed)
                    rels = relation_search_prune_local(
                        backend, entity, topic_entity[entity], pre_relations, pre_heads[i], question, args
                    )
                    ent_trace = {
                        "entity": entity,
                        "entity_name": topic_entity[entity],
                        "oracle_next_relation": oracle_next,
                        "num_relations": len(rels),
                        "oracle_rank_before_rerank": _relation_rank(rels, oracle_next),
                        "relations_before_rerank": _compact_relation_list(rels, topk=args.trace_topk),
                        "rerank": None,
                    }
                    if reranker is not None:
                        rels = reranker.rerank(backend, rels, executed)
                        ent_trace["rerank"] = reranker.last_debug
                        post_topk = int(args.diplan_post_rerank_topk or args.width)
                        ent_trace["oracle_rank_after_rerank_full"] = _relation_rank(rels, oracle_next)
                        rels = rels[: max(1, post_topk)]
                    else:
                        ent_trace["oracle_rank_after_rerank_full"] = ent_trace["oracle_rank_before_rerank"]
                    ent_trace["oracle_rank_after_keep"] = _relation_rank(rels, oracle_next)
                    ent_trace["kept_after_rerank"] = _compact_relation_list(rels, topk=args.trace_topk)
                    step_trace["entity_expansions"].append(ent_trace)
                    current_entity_relations_list.extend(rels)

                total_candidates, total_scores, total_relations = [], [], []
                total_entities_id, total_topic_entities, total_head = [], [], []
                for ent in current_entity_relations_list:
                    entity_candidates_id = backend.entity_search(ent["entity"], ent["relation"], bool(ent["head"]))
                    if len(entity_candidates_id) >= 20:
                        entity_candidates_id = random.sample(entity_candidates_id, args.num_retain_entity)
                    if not entity_candidates_id:
                        continue
                    scores, entity_candidates, entity_candidates_id = entity_score_local(
                        backend, question, entity_candidates_id, ent["score"], ent["relation"], args
                    )
                    total_candidates, total_scores, total_relations, total_entities_id, total_topic_entities, total_head = update_history(
                        entity_candidates, ent, scores, entity_candidates_id,
                        total_candidates, total_scores, total_relations,
                        total_entities_id, total_topic_entities, total_head,
                    )
                if not total_candidates:
                    step_trace["stopped"] = "no_total_candidates"
                    trace_steps.append(step_trace)
                    break
                flag, chain_of_entities, entities_id, pre_relations, pre_heads = entity_prune(
                    total_entities_id, total_relations, total_candidates,
                    total_topic_entities, total_head, total_scores, args
                )
                step_trace["selected_relations"] = list(pre_relations)
                step_trace["selected_entities"] = list(entities_id)
                step_trace["selected_heads"] = list(pre_heads)
                step_trace["oracle_next_relation"] = _oracle_next_relation(backend, executed)
                step_trace["oracle_selected"] = bool(step_trace["oracle_next_relation"] in set(pre_relations))
                if pre_relations:
                    executed.append(pre_relations[0])
                cluster_chain_of_entities.append(chain_of_entities)
                success = answer_reached(backend, entities_id)
                step_trace["answer_reached"] = bool(success)
                step_trace["continue_flag"] = bool(flag)
                trace_steps.append(step_trace)
                if success or not flag:
                    break
                topic_entity = {entity: backend.id2name(entity) for entity in entities_id}

            oracle = list(row.get("oracle_path") or [])
            trap = list(row.get("trap_path") or [])
            rec = {
                "task_id": row.get("task_id"),
                "question": question,
                "success": success,
                "executed_path": executed,
                "oracle_path": oracle,
                "trap_at_1": bool(executed and trap and executed[0] == trap[0]),
                "first_error_step": _first_error_step(executed, oracle),
            }
            trace_rec = dict(rec)
            trace_rec["steps"] = trace_steps
            records.append(rec)
            fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
            ftrace.write(json.dumps(trace_rec, ensure_ascii=False) + "\n")
            if args.show_trace and task_idx <= args.trace_limit:
                _print_trace(task_idx, trace_rec, args.trace_topk)

    summary = {
        "n": len(records),
        "hits@1": mean([1.0 if r["success"] else 0.0 for r in records]) if records else 0.0,
        "trap@1": mean([1.0 if r["trap_at_1"] else 0.0 for r in records]) if records else 0.0,
        "first_error_step": mean([r["first_error_step"] for r in records]) if records else 0.0,
    }
    if reranker:
        summary.update(reranker.diagnostics())
    else:
        summary["diplan_rerank_calls"] = 0
    with (Path(args.out) / "summary_metrics.json").open("w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)
    print(json.dumps(summary, ensure_ascii=False, indent=2))


def _first_error_step(pred, oracle):
    for i in range(min(len(pred), len(oracle))):
        if pred[i] != oracle[i]:
            return i + 1
    if len(pred) != len(oracle):
        return min(len(pred), len(oracle)) + 1
    return len(oracle) + 1


if __name__ == "__main__":
    main()
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tog_dir", required=True)
    args = parser.parse_args()

    tog_dir = Path(args.tog_dir).expanduser().resolve()
    target_dir = tog_dir / "ToG"
    if not target_dir.exists():
        raise FileNotFoundError(f"Missing official ToG/ directory: {target_dir}")
    out = target_dir / "main_subgraph_diplan.py"
    out.write_text(MAIN_SUBGRAPH_DIPLAN, encoding="utf-8")
    print({"wrote": str(out)})


if __name__ == "__main__":
    main()
